[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install -r requirements.txt" 

[deploy]
startCommand = "cd backend && gunicorn app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100

[volumes]
source = "voice_analysis_data"
destination = "/backend/data"

[[mounts]]
source = "voice_analysis_reports"
destination = "/backend/reports"

[[mounts]]
source = "voice_analysis_plots"
destination = "/backend/plots" 